language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install .
services:
    - postgresql
before_script:
    - pip install coveralls
    - pip install sqlalchemy
    - pip install pandas
    - pip install requests
script:
    - coverage run --source=sqlify setup.py test
after_success:
    - coveralls