language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install .
services:
    - postgresql
before_script:
    - pip install coveralls
script:
    - cd tests
    - python -m unittest discover
    - coverage run --source=sqlify setup.py test
after_success:
    - coveralls