language: python
python:
    - "3.5"
    - "3.6"
install:
    - pip install .
dist: trusty
sudo: required
services:
    - postgresql
addons:
    - postgresql: "9.6"
before_script:
    - psql --version
    - sudo service postgresql stop
    - sudo service postgresql start 9.6
    - pip install coveralls
    - pip install pytest-cov
    - pip install sqlalchemy
    - pip install pandas
    - pip install requests
script:
    - coverage run --source sqlify -m py.test
    - coverage report
after_success:
    - coveralls