language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install .
addons:
    - postgresql: "9.5"
before_script:
    - pip install coveralls
    - pip install pytest-cov
    - pip install sqlalchemy
    - pip install pandas
    - pip install requests
script:
    - coverage run --source sqlify -m py.test
    - coverage report
after_success:
    - coveralls